version: "1.0"
services:
  database:
    build: ./database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./database/scripts/init.sql:/docker-entrypoint-initdb.d/A_init.sql
      #- ./data:/var/lib/postgresql/data
    
  api:
    build: ./FAQ-API
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  db-data:
